import Navbar from "@/layout/adminLayout/Navbar";;
import { Metadata } from "next";
import Sidebar from '@/layout/adminLayout/Sidebar'
import { ReactNode } from "react";






export const metadata: Metadata = {
  title: "admin panel",
  description: "Generated by admin",
};



export default function AdminLayout({ children }: { children: ReactNode }) {
  return (
    <>
      <div className="flex flex-row w-full ">
        <div className="w-[20%] shadow-2xl h-screen border-r-2 border-gray-700 bg-slate-950 sticky left-0 top-0 ">
          <Sidebar />
        </div>
        <div className="w-[80%] flex flex-col ">
          <div className="bg-slate-900 p-6 sticky top-0 z-50">
            <Navbar />
          </div>

          <div className="bg-slate-950 flex-1">{children}</div>
        </div>
      </div>
    </>
  );
}
