
import Navbar from "@/layout/userLauout/Navbar";
import Footer from "@/layout/userLauout/Footer";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "User panel",
  description: "Generated by Madhumita",
};

export default function UserLayout({ children }: LayoutProps<"/">) {
  return (
    <>
    <Navbar />
    {children}
    <Footer />
    </>
    
  );
}
